name: Auto CheckVer

on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:

jobs:
  run_checkver:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Checkout bucket repository
        uses: actions/checkout@v4

      - name: Run checkver.ps1 script
        run: |
          Write-Host "Running checkver.ps1 script..."
          # 你的脚本命令
          .\bin\checkver.ps1 * -u
          Write-Host "checkver.ps1 script finished."
      - name: Commit and push changes
        run: |
          # 检查是否有文件变动
          git status --porcelain

          $changes = git status --porcelain | Measure-Object -Line

          if ($changes.Lines -gt 0) {
            Write-Host "Changes detected. Committing and pushing."

            # 配置 Git 用户信息
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"

            # 添加所有变动的文件
            git add .

            # 提交更改
            $commit_message = "Automated: Update manifests via checkver.ps1"
            git commit -m "$commit_message"

            # 推送更改到仓库
            git push origin HEAD

            Write-Host "Changes committed and pushed successfully."
          } else {
            Write-Host "No changes detected by checkver.ps1. Nothing to commit."
          }
        shell: pwsh
